### ISSUE TITLE
'NoneType' object has no attribute 'shape'

### ISSUE THREAD

**Issue by YashGulati** [omkarudawant/MICR-Retriever#1]
D:\>py -3 extract.py --image cheque.jpeg
Extracting from: cheque.jpeg
Traceback (most recent call last):
  File "extract.py", line 21, in <module>
    extracted_micr, contour_img = extract.extract_micr(image=preprocessed_img)
  File "D:\Chequebook-Information-Retriever\extraction\extract_micr.py", line 99, in extract_micr
    blackhat, gray, delta = extract_blackhat(image=image)
  File "D:\Chequebook-Information-Retriever\extraction\extract_micr.py", line 63, in extract_blackhat
    (h, w,) = image.shape[:2]
AttributeError: 'NoneType' object has no attribute 'shape'

**Comment by omkarudawant** [comment]
Hey Yash, can you check if it is resolved now?

**Comment by YashGulati** [comment]
Works now! Thanks omkarudawant,

**Comment by arpiGoud** [comment]
Hii,

Model was detecting 8 instead of 0 and 8 instead of  5 in cheque number.Please anyone help on this
